swagger: '2.0'
info:
  title: Deployments Internal API
  version: '1'
  description: |
    Internal API of deployments service

host: 'mender-deployments:8080'
basePath: '/api/internal/v1/deployments'
schemes:
  - http

produces:
  - application/json
consumes:
  - application/json

responses:
  NotFoundError: # 404
    description: Not Found.
    schema:
      $ref: "#/definitions/Error"
  InternalServerError: # 500
    description: Internal Server Error.
    schema:
      $ref: "#/definitions/Error"
  InvalidRequestError: # 400
    description: Invalid Request.
    schema:
      $ref: "#/definitions/Error"
  UnprocessableEntityError: # 422
    description: Unprocessable Entity.
    schema:
      $ref: "#/definitions/Error"

paths:
  /health:
    get:
      operationId: Check Health
      tags:
        - Internal API
      summary: Check the health of the service
      responses:
        204:
          description: >
              Service is healthy and all dependencies are up and running.
        500:
          description: >
              Unexpected internal error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              error: "internal error"
              request_id: "ffd712be-d697-4cb7-814b-88ff1e2eb5f6"
        503:
          description: >
              Service unhealthy / not ready to accept traffic. At least one
              dependency is not running.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              error: "error reaching MongoDB: context deadline exceeded"
              request_id: "ffd712be-d697-4cb7-814b-88ff1e2eb5f6"

  /alive:
    get:
      operationId: Check Liveliness
      tags:
        - Internal API
      summary: >
          Trivial endpoint that unconditionally returns an empty 200 response
          whenever the API handler is running correctly.
      responses:
        204:
          description: Service is up and running.
        500:
          description: >
              Internal API error
          schema:
            $ref: '#/definitions/Error'
  /tenants/{id}/storage/settings:
    get:
      operationId: Get Storage Settings
      tags:
        - Internal API
      summary: Get storage setting for a given tenant
      description: >
        Returns an object with per tenant storage layer specific settings.
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Successful response with all available settings.
          schema:
            $ref: "#/definitions/StorageSettings"
        500:
          description: Internal error.
          schema:
            $ref: "#/responses/InternalServerError"
    put:
      operationId: Set Storage Settings
      tags:
        - Internal API
      summary: Set storage settings for a given tenant
      description: Set the storage layer settings for a given tenant.
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: settings
          in: body
          description: |-
            Settings to set.
            If set to null or an empty object, the tenant will use the default settings.
          schema:
            $ref: "#/definitions/StorageSettings"
      responses:
        204:
          description: Settings updated.
        400:
          description: The request body is malformed.
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error.
          schema:
            $ref: "#/definitions/Error"
  /tenants/{id}/limits/storage:
    get:
      operationId: Get Storage Usage
      summary: Get storage limit and current storage usage for given tenant
      description: |
        Get storage limit and current storage usage for given tenant.
        If the limit value is 0 it means storage space is unlimited
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Successful response.
          schema:
            $ref: "#/definitions/StorageUsage"
        500:
          $ref: "#/responses/InternalServerError"
    put:
      operationId: Set Storage Limit
      summary: Set storage limit for given tenant
      description: |
        Set storage limit for given tenant.
        If the limit value is 0 it means storage space is unlimited
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: limit
          in: body
          required: true
          schema:
            $ref: "#/definitions/StorageLimit"
      responses:
        204:
          description: Limit information updated.
        400:
          description: |
              The request body is malformed.
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error.
          schema:
            $ref: "#/definitions/Error"
  /tenants:
    post:
      operationId: Create Tenant
      summary: Provision a new tenant
      description: |
          Sets up all tenant-related infrastructure, e.g. a migrated tenant's database.
      parameters:
        - name: tenant
          in: body
          description: New tenant descriptor.
          required: true
          schema:
            $ref: "#/definitions/NewTenant"
      responses:
        201:
          description: Tenant was successfully provisioned.
        400:
          description: Bad request.
        500:
          description: Internal server error.
          schema:
           $ref: "#/definitions/Error"

  /tenants/{id}/deployments:
    get:
      operationId: Get Deployments
      summary: Get all deployments for specific tenant
      description: |
        Returns a filtered collection of deployments in the system,
        including active and historical. If both 'status' and 'query' are
        not specified, all devices are listed.
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: status
          in: query
          description: Deployment status filter.
          required: false
          type: string
          enum:
            - inprogress
            - finished
            - pending
        - name: search
          in: query
          description: Deployment name or description filter.
          required: false
          type: string
        - name: page
          in: query
          description: Results page number
          required: false
          type: number
          format: integer
          default: 1
        - name: created_before
          in: query
          description: List only deployments created before and equal to Unix timestamp (UTC)
          required: false
          type: number
          format: integer
        - name: created_after
          in: query
          description: List only deployments created after and equal to Unix timestamp (UTC)
          required: false
          type: number
          format: integer
      produces:
        - application/json
      responses:
        200:
          description: Successful response.
          examples:
            application/json:
              - created: 2016-02-11T13:03:17.063493443Z
                status: finished
                name: production
                artifact_name: Application 0.0.1
                id: 00a0c91e6-7dec-11d0-a765-f81d4faebf6
                finished: 2016-03-11T13:03:17.063493443Z
                device_count: 10
          schema:
            type: array
            items:
              $ref: '#/definitions/Deployment'
          headers:
            X-Total-Count:
              type: integer
              description: Total number of deployments matching query.
        400:
          $ref: "#/responses/InvalidRequestError"

  /tenants/{tenant_id}/deployments/devices:
    get:
      operationId: List Device Deployments entries
      tags:
        - Internal API
      summary: Return the Deployments history entries for the specified IDs
      description: |
        Return the Deployments history entries for the specified IDs
      parameters:
        - name: tenant_id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: id
          in: query
          description: Deployment Device ID filter. Can be repeated to query a set of entries.
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/DeviceDeployment"
        400:
          description: Bad request.
        500:
          description: Internal server error.
          schema:
              $ref: "#/definitions/Error"

  /tenants/{tenant_id}/deployments/devices/{id}:
    get:
      operationId: List Deployments for a Device
      tags:
        - Internal API
      summary: Return the Deployments history for a Device
      description: |
        Return the Deployments history for the specified Device, listing all its Deployments.
      parameters:
        - name: tenant_id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: id
          in: path
          description: System wide device identifier
          required: true
          type: string
        - name: status
          in: query
          description: >-
            Filter deployments by status for the given device.
          type: string
          enum: # Unfortunately swagger 2.0 does not support reuse of enums.
            - "failure"
            - "aborted"
            - "pause_before_installing"
            - "pause_before_committing"
            - "pause_before_rebooting"
            - "downloading"
            - "installing"
            - "rebooting"
            - "pending"
            - "success"
            - "noartifact"
            - "already-installed"
            - "decommissioned"
            - "pause"
            - "active"
            - "finished"
          required: false
        - name: page
          in: query
          description: Starting page.
          required: false
          type: number
          format: integer
          default: 1
        - name: per_page
          in: query
          description: Maximum number of results per page.
          required: false
          type: number
          format: integer
          default: 20
          maximum: 20
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/DeviceDeployment"
        500:
          description: Internal server error.
          schema:
              $ref: "#/definitions/Error"
    delete:
      operationId: Remove Device from Deployments
      tags:
        - Internal API
      summary: Remove device from all deployments
      description: Set 'decommissioned' status to all pending device deployments for a given device
      parameters:
        - name: tenant_id
          in: path
          type: string
          description: Tenant ID
          required: true
        - name: id
          in: path
          description: System wide device identifier
          required: true
          type: string
      responses:
        204:
          description: Device was removed
        500:
          description: Internal server error.
          schema:
              $ref: "#/definitions/Error"

  /tenants/{id}/artifacts:
    post:
      operationId: Upload artifact
      summary: Upload mender artifact
      description: |
        Upload mender artifact to a specific tenant. Multipart request with meta and artifact.
        Supports artifact [versions v1, v2, v3](https://docs.mender.io/overview/artifact#versions).
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: path
          type: string
          description: Tenant ID, or "default" if running in non-multitenant setup
          required: true
        - name: artifact_id
          in: formData
          required: false
          description: Artifact ID, optional; the server generates a randome one if not provided.
          type: string
        - name: size
          in: formData
          description: Size of the artifact file in bytes.
          required: false
          type: integer
          format: long
        - name: description
          in: formData
          required: false
          type: string
        - name: artifact
          in: formData
          description: Artifact. It has to be the last part of request.
          required: true
          type: file
      produces:
        - application/json
      responses:
        201:
          description: Artifact uploaded.
          headers:
            Location:
              description: URL of the newly uploaded artifact.
              type: string
        400:
          $ref: "#/responses/InvalidRequestError"
        500:
          $ref: "#/responses/InternalServerError"
  /tenants/{tenant_id}/configuration/deployments/{deployment_id}/devices/{device_id}:
    post:
      operationId: Create Deployment
      tags:
        - Internal API
      summary: Create a configuration deployment
      description: |
        Deploy configuration to a specified device.
        The artifact will be auto-generated based on the configuration object
        provided with the deployment constructor.
      parameters:
        - name: tenant_id
          in: path
          description: Tenant identifier.
          required: true
          type: string
        - name: device_id
          in: path
          description: Device identifier.
          required: true
          type: string
        - name: deployment_id
          in: path
          description: Deployment identifier.
          required: true
          type: string
        - name: deployment
          in: body
          description: New deployment that needs to be created.
          required: true
          schema:
            $ref: "#/definitions/NewConfigurationDeployment"
      produces:
        - application/json
      responses:
        201:
          description: New configuration deployment created.
          headers:
            Location:
              description: URL of the newly created deployment.
              type: string
        400:
          $ref: "#/responses/InvalidRequestError"
        409:
          description: The deployment with a given id already exists.
          schema:
            $ref: "#/definitions/Error"
        500:
          $ref: "#/responses/InternalServerError"

  /tenants/{tenant_id}/devices/deployments/last:
    post:
      operationId: Get last device deployment status
      tags:
        - Internal API
      summary: Get status of the last device devployment
      description: |
        Return the status of the last unsucessful device deployment.
      parameters:
        - name: tenant_id
          in: path
          description: Tenant identifier.
          required: true
          type: string
        - name: devicesIds
          in: body
          description: An array of device ids for which to return the statuses.
          schema:
            type: array
            items:
              type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: List of device deployment statuses returned.
        400:
          $ref: "#/responses/InvalidRequestError"
        500:
          $ref: "#/responses/InternalServerError"

definitions:
  NewTenant:
    description: New tenant descriptor.
    type: object
    properties:
      tenant_id:
        description: New tenant's ID.
        type: string
    example:
      tenant_id: "58be8208dd77460001fe0d78"

  Error:
    description: Error descriptor.
    type: object
    properties:
      error:
        description: Description of the error.
        type: string
      request_id:
        description: Request ID (same as in X-MEN-RequestID header).
        type: string
    example:
      error: "error message"
      request_id: "f7881e82-0492-49fb-b459-795654e7188a"
  StorageSettings:
    description: Per tenant storage settings.
    type: object
    properties:
      type:
        type: string
        enum:
          - s3
          - azure
        description: >-
          The storage provider type 'azure' Blob storage or AWS 's3' (defaults to s3).
      region:
        type: string
        description: >-
          AWS region (S3 only: required).
      bucket:
        type: string
        description: >-
          S3 Bucket (Azure: container) name.
      uri:
        type: string
        description: >-
          Bucket/container endpoint URI.
      external_uri:
        type: string
        description: Public Endpoint URI for presigning URLs (S3 only).
      key:
        type: string
        description: >-
          Access key identifier (Azure: account name).
      secret:
        type: string
        description: >-
          Secret access key (Azure: access key).
      token:
        type: string
        description: AWS S3 session token (S3 only).
      force_path_style:
        type: boolean
        description: Force S3 path-style instead of virtual-hosted style (S3 only).
      use_accelerate:
        type: boolean
        description: Enable S3 Transfer acceleration (S3 only).
      connection_string:
        type: string
        description: Shared access key connection string (Azure only).
      container_name:
        type: string
        description: >-
          Alias for 'bucket' (Azure only).
      account_name:
        type: string
        description: >-
          Alias for 'key' (Azure only).
      account_key:
        type: string
        description: >-
          Alias for 'secret' (Azure only).
    required:
      - bucket
      - key
      - secret
    example:
      region: us-east-1
      bucket: mender-artifacts-unique-bucket-name
      uri: example.internal:9000
      external_uri: example.com
      key: <key>
      secret: <secret>
      token: <token>
      force_path_style: false
      use_accelerate: false
  StorageUsage:
    description: Tenant account storage limit and storage usage.
    type: object
    properties:
      limit:
        type: integer
        description: |
            Storage limit in bytes. If set to 0 - there is no limit for storage.
      usage:
        type: integer
        description: |
            Current storage usage in bytes.
    required:
      - limit
      - usage
    example:
      limit: 1073741824
      usage: 536870912
  StorageLimit:
    description: Tenant account storage limit
    type: object
    properties:
      limit:
        type: integer
        description: |
            Storage limit in bytes. If set to 0 - there is no limit for storage.
    required:
      - limit
    example:
      limit: 1073741824
  Deployment:
    type: object
    properties:
      created:
        type: string
        format: date-time
      name:
        type: string
      artifact_name:
        type: string
      id:
        type: string
      finished:
        type: string
        format: date-time
      status:
        type: string
        enum:
          - inprogress
          - pending
          - finished
      device_count:
        type: integer
      artifacts:
        type: array
        description: An array of artifact's identifiers.
        items:
          type: string
      type:
        type: string
        enum:
          - configuration
          - software
    required:
      - created
      - name
      - artifact_name
      - id
      - status
    example:
      created: 2016-02-11T13:03:17.063493443Z
      status: finished
      name: production
      artifact_name: Application 0.0.1
      id: 00a0c91e6-7dec-11d0-a765-f81d4faebf6
      finished: 2016-03-11T13:03:17.063493443Z
  NewConfigurationDeployment:
    type: object
    properties:
      name:
        type: string
        description: Name of the deployment
      configuration:
        type: string
        description: |
            A string containing a configuration object.
            The deployments service will use it to generate configuration
            artifact for the device.
            The artifact will be generated when the device will ask
            for an update.
    required:
      - name
      - configuration
    example:
      name: config-1.1
      configuration: "{\"foo\":\"bar\"}"
  DeviceDeployment:
    type: object
    properties:
      id:
        type: string
      deployment:
        $ref: "#/definitions/Deployment"
      device:
        $ref: "#/definitions/DeviceWithImage"
    required:
      - deployment
      - device
    example:
      id: 0c13a0e6-6b63-475d-8260-ee42a590e8ff
      deployment:
        id: 00a0c91e6-7dec-11d0-a765-f81d4faebf6
        name: production
        artifact_name: Application 0.0.1
        status: inprogress
        created: 2016-02-11T13:03:17.063493443Z
        device_count: 100
      device:
        id: 00a0c91e6-7dec-11d0-a765-f81d4faebf6
        device_type: Raspberry Pi 3
        status: installing
        finished: 2016-03-11T13:03:17.063493443Z
        created: 2016-02-11T13:03:17.063493443Z
        state: installing
        substate: installing.enter;script:foo-bar
        log: false
        image:
          id: 0c13a0e6-6b63-475d-8260-ee42a590e8ff
          name: Application 1.0.0
          meta:
            description: Johns Monday test build
          meta_artifact:
            name: Application 1.0.0
            device_types_compatible: [Beagle Bone]
            info:
              type_info:
                type: rootfs
            signed: false
            updates:
              type_info: "rootfs-image"
              files:
                - name: rootfs-image-1
                  checksum: cc436f982bc60a8255fe1926a450db5f195a19ad
                  size: 123
                  date: 2016-03-11T13:03:17.063+0000
              meta_data: {}
            artifact_provides:
              artifact_name: "test"
              rootfs-image.checksum: "32714818ad6f98ee0185a52e23a475d89122e3efd2b2c26c733781c28e798c99"
              rootfs-image.version: "test"
            artifact_depends:
              device_type:
                - "test"
            clears_artifact_provides:
              - "rootfs-image.*"
          size: 36891648
          modified: "2016-03-11T13:03:17.063493443Z"
  DeviceWithImage:
    type: object
    properties:
      id:
        type: string
        description: Device identifier.
      status:
        $ref: '#/definitions/DeviceStatus'
      created:
        type: string
        format: date-time
      finished:
        type: string
        format: date-time
      deleted:
        type: string
        format: date-time
      device_type:
        type: string
      log:
        type: boolean
        description: Availability of the device's deployment log.
      state:
        type: string
        description: State reported by device
      substate:
        type: string
        description: Additional state information
      image:
        type: object
        properties:
          id:
            type: string
            description: Image ID
          meta:
            type: object
            properties:
              description:
                type: string
                description: Image description
          meta_artifact:
            type: object
            properties:
              name:
                type: string
              device_types_compatible:
                type: array
                description: An array of compatible device types.
                items:
                  type: string
              info:
                $ref: "#/definitions/ArtifactInfo"
              signed:
                type: boolean
                description: Idicates if artifact is signed or not.
              updates:
                type: array
                items:
                  $ref: "#/definitions/Update"
              artifact_provides:
                type: object
                description: |
                  List of Artifact provides.

                  Map of key/value pairs, where both keys and values are strings.
                additionalProperties:
                  type: string
              artifact_depends:
                type: object
                description: |
                  List of Artifact depends.

                  Map of key/value pairs, where keys are strings and values are lists of strings.
                additionalProperties:
                  type: array
                  items:
                    type: string
              clears_artifact_provides:
                type: array
                description: List of Clear Artifact provides.
                items:
                  type: string
          size:
            type: integer
            description: Image size in bytes
          modified:
            type: string
            format: date-time
            description: Creation / last edition of any of the artifact properties
    required:
      - id
      - status
      - log
    example:
      id: 00a0c91e6-7dec-11d0-a765-f81d4faebf6
      finished: 2016-03-11T13:03:17.063493443Z
      status: installing
      created: 2016-02-11T13:03:17.063493443Z
      device_type: Raspberry Pi 3
      log: false
      state: installing
      substate: installing.enter;script:foo-bar
      image:
        id: 0c13a0e6-6b63-475d-8260-ee42a590e8ff
        name: Application 1.0.0
        meta:
          description: Johns Monday test build
        meta_artifact:
          name: Application 1.0.0
          device_types_compatible: [Beagle Bone]
          info:
            type_info:
              type: rootfs
          signed: false
          updates:
            type_info: "rootfs-image"
            files:
              - name: rootfs-image-1
                checksum: cc436f982bc60a8255fe1926a450db5f195a19ad
                size: 123
                date: 2016-03-11T13:03:17.063+0000
            meta_data: {}
          artifact_provides:
            artifact_name: "test"
            rootfs-image.checksum: "32714818ad6f98ee0185a52e23a475d89122e3efd2b2c26c733781c28e798c99"
            rootfs-image.version: "test"
          artifact_depends:
            device_type:
              - "test"
          clears_artifact_provides:
            - "rootfs-image.*"
        size: 36891648
        modified: "2016-03-11T13:03:17.063493443Z"
  DeviceStatus:
    type: string
    enum:
      - "failure"
      - "aborted"
      - "pause_before_installing"
      - "pause_before_committing"
      - "pause_before_rebooting"
      - "downloading"
      - "installing"
      - "rebooting"
      - "pending"
      - "success"
      - "noartifact"
      - "already-installed"
      - "decommissioned"
  ArtifactTypeInfo:
      description: |
          Information about update type.
      type: object
      properties:
        type:
          type: string
          description: Note that for emtpy Artifacts, the type is 'null'
  UpdateFile:
      description: |
          Information about particular update file.
      type: object
      properties:
        name:
          type: string
        checksum:
          type: string
        size:
          type: integer
        date:
          type: string
          format: date-time
  Update:
      description: |
          Single updated to be applied.
      type: object
      properties:
        type_info:
          $ref: "#/definitions/ArtifactTypeInfo"
        files:
          type: array
          items:
            $ref: "#/definitions/UpdateFile"
        meta_data:
          type: object
          description: |
              meta_data is an object of unknown structure as this is dependent of update type (also custom defined by user)
  ArtifactInfo:
      description: |
          Information about artifact format and version.
      type: object
      properties:
        format:
          type: string
        version:
          type: integer
